name: katib ci build & push for ${{ github.ref_name }}

on:
  push:
    tags:
      - "katib-v*.*"

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./katib
    steps:
      - uses: actions/checkout@v6
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#katib-}" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        # NOtE: we can harden this by pinning to the commit SHA (5e57cd118135c172c3672efd75eb46360885c0ef)
        # to prevent supply chain attacks
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./katib
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/katib:${{ steps.version.outputs.VERSION }},${{ vars.DOCKERHUB_USERNAME }}/katib:latest
          # remote layer caching to speed up builds
          # on aws we would use a specific tag in the ecr repo for this like `buildcache`
          cache-from: type=gha
          cache-to: type=gha,mode=max
